// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package gods

type NDArrInt struct {
	Data []int
}

func (a NDArrInt) String() string {
	return "I'm a array of Ints"
}

type NDArrInt8 struct {
	Data []int8
}

func (a NDArrInt8) String() string {
	return "I'm a array of Int8s"
}

type NDArrInt16 struct {
	Data []int16
}

func (a NDArrInt16) String() string {
	return "I'm a array of Int16s"
}

type NDArrInt32 struct {
	Data []int32
}

func (a NDArrInt32) String() string {
	return "I'm a array of Int32s"
}

type NDArrInt64 struct {
	Data []int64
}

func (a NDArrInt64) String() string {
	return "I'm a array of Int64s"
}

type NDArrUint struct {
	Data []uint
}

func (a NDArrUint) String() string {
	return "I'm a array of Uints"
}

type NDArrUint8 struct {
	Data []uint8
}

func (a NDArrUint8) String() string {
	return "I'm a array of Uint8s"
}

type NDArrUint16 struct {
	Data []uint16
}

func (a NDArrUint16) String() string {
	return "I'm a array of Uint16s"
}

type NDArrUint32 struct {
	Data []uint32
}

func (a NDArrUint32) String() string {
	return "I'm a array of Uint32s"
}

type NDArrUint64 struct {
	Data []uint64
}

func (a NDArrUint64) String() string {
	return "I'm a array of Uint64s"
}

type NDArrFloat32 struct {
	Data []float32
}

func (a NDArrFloat32) String() string {
	return "I'm a array of Float32s"
}

type NDArrFloat64 struct {
	Data []float64
}

func (a NDArrFloat64) String() string {
	return "I'm a array of Float64s"
}
