// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package gods

type ArrInt struct {
	Data  []int
	Shape []int
}

func (a ArrInt) String() string {
	return "I'm a array of Ints"
}

type ArrInt8 struct {
	Data  []int8
	Shape []int
}

func (a ArrInt8) String() string {
	return "I'm a array of Int8s"
}

type ArrInt16 struct {
	Data  []int16
	Shape []int
}

func (a ArrInt16) String() string {
	return "I'm a array of Int16s"
}

type ArrInt32 struct {
	Data  []int32
	Shape []int
}

func (a ArrInt32) String() string {
	return "I'm a array of Int32s"
}

type ArrInt64 struct {
	Data  []int64
	Shape []int
}

func (a ArrInt64) String() string {
	return "I'm a array of Int64s"
}

type ArrUint struct {
	Data  []uint
	Shape []int
}

func (a ArrUint) String() string {
	return "I'm a array of Uints"
}

type ArrUint8 struct {
	Data  []uint8
	Shape []int
}

func (a ArrUint8) String() string {
	return "I'm a array of Uint8s"
}

type ArrUint16 struct {
	Data  []uint16
	Shape []int
}

func (a ArrUint16) String() string {
	return "I'm a array of Uint16s"
}

type ArrUint32 struct {
	Data  []uint32
	Shape []int
}

func (a ArrUint32) String() string {
	return "I'm a array of Uint32s"
}

type ArrUint64 struct {
	Data  []uint64
	Shape []int
}

func (a ArrUint64) String() string {
	return "I'm a array of Uint64s"
}

type ArrFloat32 struct {
	Data  []float32
	Shape []int
}

func (a ArrFloat32) String() string {
	return "I'm a array of Float32s"
}

type ArrFloat64 struct {
	Data  []float64
	Shape []int
}

func (a ArrFloat64) String() string {
	return "I'm a array of Float64s"
}
