// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package gods

type ArrInt struct {
	Data []int
}

func (a ArrInt) String() string {
	return "I'm a Int array"
}

type ArrInt32 struct {
	Data []int32
}

func (a ArrInt32) String() string {
	return "I'm a Int32 array"
}

type ArrInt64 struct {
	Data []int64
}

func (a ArrInt64) String() string {
	return "I'm a Int64 array"
}

type ArrFloat32 struct {
	Data []float32
}

func (a ArrFloat32) String() string {
	return "I'm a Float32 array"
}

type ArrFloat64 struct {
	Data []float64
}

func (a ArrFloat64) String() string {
	return "I'm a Float64 array"
}
